name: binrep
version: 0.2.0
synopsis: Encode precise binary representations directly in types
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Data, Serialization
tested-with: GHC ==9.2.2
license: MIT
license-file: LICENSE

github: raehik/binrep
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# TODO 2022-04-22 This will be supported eventually - I looked just now, and
# there was a fix 10 hours ago! But it'll take a while to trickle down into an
# hpack release, and then that release in Stack.
language: GHC2021

# raehik's extensions (GHC 9.2; last updated: 2022-06-15)
default-extensions:
# syntax that should be default
- EmptyCase
- LambdaCase
- InstanceSigs
- BangPatterns
- ExplicitNamespaces # 7.6

## deriving-related
- DerivingStrategies # 8.2
- DerivingVia # 8.6
- StandaloneDeriving
- DeriveAnyClass
- DeriveGeneric
- DeriveDataTypeable
- DeriveFunctor
- DeriveFoldable
- DeriveTraversable
- DeriveLift

# features that should be default
- FlexibleContexts
- FlexibleInstances
- MultiParamTypeClasses
- GADTs
- PolyKinds
- RoleAnnotations # 7.8
- RankNTypes

# other features
- TypeApplications # 8.0
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash
- ImportQualifiedPost # 8.10
- StandaloneKindSignatures # 8.10

# essential, but can break things, so be wary
- ScopedTypeVariables # changes type var scoping quite dramatically
- TypeOperators # interferes with the old `*` type

# useful extensions to know about, but which must be specified on-demand
#- UndecidableInstances

ghc-options:
- -Wall

dependencies:
- base >= 4.14 && < 5
- bytestring ^>= 0.11
- refined ^>= 0.7
- aeson ^>= 2.0 # because we use refined which uses it (also for HexByteString)
- text ^>= 1.2
- either ^>= 5.0.1.1
- megaparsec ^>= 9.2.0 # for HexByteString
- mason ^>= 0.2.5
- vector-sized ^>= 1.5.0
- vector ^>= 0.12.3.1
- strongweak ^>= 0.3.1
- either ^>= 5.0.1.1
- text-icu ^>= 0.8.0.1
- flatparse ^>= 0.3.5.0

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    build-tools:
    - hspec-discover >= 2.7 && < 2.10
    dependencies:
    - binrep
    - hspec >= 2.7 && < 2.10
    - QuickCheck ^>= 2.14.2
    - quickcheck-instances ^>= 0.3.26
    - generic-random ^>= 1.5.0.1
