name: binrep
version: 0.5.0
synopsis: Encode precise binary representations directly in types
description: Please see README.md.
extra-source-files:
- README.md
- CHANGELOG.md
category: Data, Serialization
tested-with: GHC ==9.4.4
license: MIT
license-file: LICENSE

github: raehik/binrep
maintainer: Ben Orchard <thefirstmuffinman@gmail.com>
author: Ben Orchard

# raehik's extensions (GHC 9.2; last updated: 2022-10-09)
language: GHC2021
default-extensions:
# syntax that should be default
- LambdaCase
- NoStarIsType

## deriving-related
- DerivingVia # implies DerivingStrategies
- DeriveAnyClass

# features that should be default
- GADTs
- RoleAnnotations

# other features
- DefaultSignatures
- TypeFamilies
- DataKinds

# other syntax
- MagicHash

# useful extensions to know about, but which should be specified on-demand
#
# UndecidableInstances:
#   required for type class wizardry
#   generally only enable if you were expecting to & compilation fails without
# AllowAmbiguousTypes:
#   often goes hand in hand with TypeApplications-heavy code
#   enabling on demand brings attention to the sort of functions to expect
# StarIsType:
#   may need to enable if you're working with old code that uses `Int :: *`

ghc-options:
- -Wall

dependencies:
- base >= 4.14 && < 5
- flatparse ^>= 0.4.0.1
- parser-combinators ^>= 1.3.0
- bytestring ^>= 0.11
- strongweak ^>= 0.6.0
- refined1 ^>= 0.9
- text ^>= 2
- vector-sized ^>= 1.5.0
- vector ^>= 0.12.3.1
- deepseq ^>= 1.4.8.0

- megaparsec ^>= 9.2.0 # for HexByteString
- aeson >= 2.0 && < 2.2 # because we use refined which uses it (also for HexByteString)

# TODO
- mason

library:
  source-dirs: src

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    build-tools:
    - hspec-discover >= 2.7 && < 2.10
    dependencies:
    - binrep
    - hspec >= 2.7 && < 2.10
    - QuickCheck ^>= 2.14.2
    - quickcheck-instances ^>= 0.3.26
    - generic-random ^>= 1.5.0.1

flags:
  icu:
    description: use text-icu package (requires ICU library)
    default: true
    manual: true

when:
- condition: flag(icu)
  dependencies:
  - text-icu >= 0.7.0.0 && < 0.9
  cpp-options:
  - -DHAVE_ICU

benchmarks:
  bench:
    source-dirs: bench
    main: Main.hs
    dependencies:
    - binrep
    - gauge
    ghc-options:
    - -O2
