resolver: nightly-2022-03-30
packages: [.]

extra-deps:
# currently depends on my predicate polykind fix
- git: https://github.com/raehik/refined
  commit: 952e0348348aaf11c8b93c6e1ac6d33a0cbbb6b1

# currently depends on my EOF getter
- git: https://github.com/raehik/cereal
  commit: 1c2e1fc36bb1cd18eb4843a0998b938464005b01
