resolver: nightly-2022-03-30
packages: [.]

extra-deps:
# currently depends on my predicate polykind fix
- git: https://github.com/raehik/refined
  commit: 952e0348348aaf11c8b93c6e1ac6d33a0cbbb6b1

# my EOF getter improves performance
#- git: https://github.com/raehik/cereal
#  commit: 1c2e1fc36bb1cd18eb4843a0998b938464005b01

# super fast bytestring serializer
- mason-0.2.5@sha256:44ead52c404f49006e4759d746b9008f8a6b2c642cbb27d26e7e25e7ba9a6f71,1221
