name: Nix

on:
  push:

jobs:
  nix-build:
    name: nix build .#${{ matrix.ghc }}-binrep
    strategy:
      fail-fast: false
      matrix:
        ghc: [ghc98, ghc910]
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "read"
    steps:
    - uses: actions/checkout@v4
    - uses: DeterminateSystems/nix-installer-action@main
    - uses: DeterminateSystems/magic-nix-cache-action@main
    - uses: DeterminateSystems/flake-checker-action@main
    - run: nix build .#${{ matrix.ghc }}-binrep
